**Important: This notebook will only work with fastai-0.7.x. Do not try to run any fastai-1.x code from this path in the repository because it will load fastai-0.7.x**

## Image classification with Convolutional Neural Networks

In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
# This file contains all the main external libs we'll use
from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

In [10]:
PATH = "../../../data/dogscats/"
sz=224
arch=vgg16
bs=64

In [11]:
# Uncomment the below if you need to reset your precomputed activations
# !rm -rf {PATH}tmp

In [12]:
data = ImageClassifierData.from_paths(PATH, bs=bs, tfms=tfms_from_model(arch, sz))

In [13]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

Downloading: "https://download.pytorch.org/models/vgg16_bn-6c64b313.pth" to /home/sidd/.torch/models/vgg16_bn-6c64b313.pth
100%|██████████| 553507836/553507836 [00:15<00:00, 34804027.42it/s]


100%|██████████| 32/32 [00:25<00:00,  1.56it/s]


In [14]:
learn.fit(0.01, 3, cycle_len=1)


epoch      trn_loss   val_loss   accuracy                     
    0      0.061072866298602375 [0.02958]  0.991     
    1      0.04340787239835176 [0.03073]  0.9895              
    2      0.043891069762058865 [0.02444]  0.993              


[array([0.02444]), 0.993]

In [15]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)

In [16]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs, num_workers=4)
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [17]:
learn.fit(1e-2, 2)


epoch      trn_loss   val_loss   accuracy                     
    0      0.05970521386843249 [0.03823]  0.986     
    1      0.04730572382507246 [0.02856]  0.9885              


[array([0.02856]), 0.9885]

In [18]:
learn.precompute=False

In [19]:
learn.fit(1e-2, 1, cycle_len=1)


epoch      trn_loss   val_loss   accuracy                     
    0      0.045788753061667825 [0.02705]  0.99      


[array([0.02705]), 0.99]

In [20]:
learn.unfreeze()

In [21]:
lr=np.array([1e-4,1e-3,1e-2])

In [22]:
learn.fit(lr, 1, cycle_len=1)


epoch      trn_loss   val_loss   accuracy                     
    0      0.05557424881873467 [0.02811]  0.9885    


[array([0.02811]), 0.9885]

In [ ]:
learn.fit(lr, 3, cycle_len=1, cycle_mult=2)

A Jupyter Widget

[ 0.       0.05955  0.02217  0.9917 ]                         
[ 1.       0.03902  0.0181   0.99414]                         
[ 2.       0.03676  0.0168   0.99414]                         
[ 3.       0.03097  0.01607  0.99316]                         
[ 4.       0.02823  0.01574  0.99316]                         
[ 5.       0.02663  0.01448  0.99316]                         
[ 6.       0.03113  0.01642  0.99414]                         



In [ ]:
learn.fit(lr, 3, cycle_len=3)

A Jupyter Widget

[ 0.       0.02769  0.01896  0.99268]                         
[ 1.       0.01939  0.01417  0.99365]                         
[ 2.       0.01935  0.0142   0.99414]                         
[ 3.       0.02465  0.01641  0.99316]                         
[ 4.       0.02753  0.01376  0.99365]                         
[ 5.       0.01721  0.01413  0.99414]                         
[ 6.       0.0221   0.01317  0.99365]                         
[ 7.       0.01789  0.01379  0.99268]                         
[ 8.       0.01861  0.0139   0.99316]                         



In [ ]:
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0);accuracy_np(probs,y)

0.995